### ISSUE TITLE
NO MAN’S SKY: SENTINEL UPDATE

### ISSUE THREAD

**Issue by Semon-47** [zencq/Pi#2]
Please
After the sentinel version was updated, there were some changes in the upgraded module data. 
The strength of personal Defence Systems was all reduced;(UP_SHLD1-X)
the damage of Pulse Spitter and all Vehicles Mounted Cannon were reduced;(UP_SMG1-X,UP_EXGUN1-4,UP_SUGUN1-4,UP_MCGUN2-4,)
The damage of Plasma Launcher was doubled;(UP_GREN1-X)
The Neutron Cannon was missing from C, B and A. (UP_CANN1-3)
Can you update it if it's convenient for you? Thank you very much!

**Comment by cengelha** [comment]
Sure! The Neutron Cannon is now complete, and I'll have a look at the others over the next days.
- [ ] UP_SHLD
- [ ] UP_SMG
- [ ] UP_EXGUN
- [ ] UP_SUGUN
- [ ] UP_MCGUN
- [ ] UP_GREN

**Comment by Semon-47** [comment]
> Sure! The Neutron Cannon is now complete, and I'll have a look at the others over the next days.
> 
> * [ ]  UP_SHLD
> * [ ]  UP_SMG
> * [ ]  UP_EXGUN
> * [ ]  UP_SUGUN
> * [ ]  UP_MCGUN
> * [ ]  UP_GREN

Thanks

**Comment by cengelha** [comment]
I updated the comment above with all items that have changed values. I'll use it to track progress.

All except the `UP_SHLD` are more of a bugfix than a real change.

**Comment by Semon-47** [comment]
> Sure! The Neutron Cannon is now complete, and I'll have a look at the others over the next days.
> 
> AlienShip
> 
> * [x]  UA_PULSE1
> * [x]  UA_PULSE2
> 
> Exocraft
> 
> * [x]  UP_EXGUN1
> * [x]  UP_EXGUN2
> * [x]  UP_EXGUN3
> * [x]  UP_EXGUN4
> 
> Mech
> 
> * [x]  UP_MCGUN2
> * [x]  UP_MCGUN3
> * [x]  UP_MCGUN4
> 
> Ship
> 
> * [x]  UP_PULSE1
> * [x]  UP_PULSE2
> * [x]  UP_PULSEX
> * [x]  UP_LAUN1
> * [x]  UP_LAUNX
> 
> Submarine
> 
> * [x]  UP_SUGUN1
> * [x]  UP_SUGUN2
> * [x]  UP_SUGUN3
> * [x]  UP_SUGUN4
> 
> Suit
> 
> * [x]  UP_ENGY1
> * [x]  UP_ENGY2
> * [x]  UP_ENGYX
> * [x]  UP_JET1
> * [x]  UP_JET2
> * [x]  UP_JET3
> * [x]  UP_JETX
> * [x]  UP_SHLD1
> * [x]  UP_SHLD2
> * [x]  UP_SHLD3
> * [x]  UP_SHLD4
> * [x]  UP_SHLDX
> * [x]  UP_SNSUIT
> 
> Weapon
> 
> * [x]  UP_LASER1
> * [x]  UP_LASERX
> * [x]  UP_BOLT1
> * [x]  UP_BOLTX
> * [x]  UP_GREN1
> * [x]  UP_GREN2
> * [x]  UP_GREN3
> * [x]  UP_GREN4
> * [x]  UP_GRENX
> * [x]  UP_SHOT2
> * [x]  UP_SHOTX
> * [x]  UP_SMG1
> * [x]  UP_SMG2
> * [x]  UP_SMG3
> * [x]  UP_SMG4
> * [x]  UP_SMGX
> * [x]  UP_CANN1
> * [x]  UP_CANN2
> * [x]  UP_CANN3
> * [x]  UP_CANN4
> * [x]  UP_CANNX
> * [x]  UP_SENGUN

It was absolutely excellent. Thanks so much！
