### ISSUE TITLE
Waypoint

### ISSUE THREAD

**Issue by cengelha** [zencq/Pi#5]
Overview and progress tracker of changed items in the the Waypoint update:

Suit
- [ ] UP_JET2
- [ ] UP_JET3
- [ ] UP_JET4
- [ ] UP_JETX
- [ ] UP_SNSUIT

Ship
- [ ] UP_PULSE1
- [ ] UP_PULSE2
- [ ] UP_PULSE3
- [ ] UP_PULSE4
- [ ] UP_PULSEX
- [ ] UP_HYP1
- [ ] UP_HYP2
- [ ] UP_HYP3
- [ ] UP_HYP4
- [ ] UP_HYPX

AlienShip
- [ ] UA_SLASR1
- [ ] UA_SLASR2
- [ ] UA_SLASR3
- [ ] UA_SLASR4
- [ ] UA_PULSE1
- [ ] UA_PULSE2
- [ ] UA_PULSE3
- [ ] UA_PULSE4
- [ ] UA_HYP1
- [ ] UA_HYP2
- [ ] UA_HYP3
- [ ] UA_HYP4

Weapon
- [ ] UP_SCAN1
- [ ] UP_SCAN2
- [ ] UP_SCAN3
- [ ] UP_SCAN4
- [ ] UP_SCANX
- [x] UP_LASERX

**Comment by AutumnGamer** [comment]
Are you also planning to add the Scanner modules to this list? They have received a major overhaul with individual stats for fauna, flora and minerals, and their scan radius stats have also changed. Thank you very much for this great resource!
