### ISSUE TITLE
UP_CANN4.csv has incorrect values for Weapon_Projectile_Damage

### ISSUE THREAD

**Issue by garywilliams** [zencq/Pi#7]
Every entry in UP_CANN4.csv has Weapon_Projectile_Damage = 10, which is incorrect. This value should vary from 10 to 14.

This file is of particular interest because the S-class upgrades are superior to the X-class upgrades for this particular weapon, and with a supercharged slot arrangement that is "almost square", the neutron cannon is the most powerful weapon in the game, with damage potential > 180,000.

Nobody seems to know what the best upgrade module seed is because the perfection column is incorrect because the weapon_projectile_damage column is incorrect.

**Comment by AmbicatusCelta** [comment]
![Screenshot 2024-02-20 183240](https://github.com/zencq/Pi/assets/102988108/3082ec45-1536-49a1-af33-4bee1ae65e7a)
this value vary from 10 to 15...

**Comment by garywilliams** [comment]
[AmbicatusCelta](https://github.com/AmbicatusCelta), do you know what seed is that upgrade you showed?

**Comment by garywilliams** [comment]
AmbicusCata, that screenshot shows the module in a supercharged slot. If it were placed in a non-supercharged slot, the damage would be lower than 15%.

**Comment by Lenni009** [comment]
Wouldn't the stats be yellow if the upgrade was in a supercharged slot?

**Comment by garywilliams** [comment]
> Wouldn't the stats be yellow if the upgrade was in a supercharged slot?

NMS isn't very consistent with colors. We'd also expect the red stripe to be yellow. But "sobrecargada" means "overloaded" in Spanish.

**Comment by garywilliams** [comment]
> Wouldn't the stats be yellow if the upgrade was in a supercharged slot?

My mistake. "Sobrecargada" means "overloaded". I thought it was "supercharged", but the stripe should be yellow in that case.

**Comment by garywilliams** [comment]
It would be awesome if we could find out the seed that corresponds to that upgrade. My best guess is that the original English name would have been "Supreme Compression Laser". If I'm right, then there are 2,121 possible seeds with that name.

**Comment by skyhirider** [comment]
I thought the X class for neutron cannon was bugged and always worse than S class?

**Comment by garywilliams** [comment]
> I thought the X class for neutron cannon was bugged and always worse than S class?

Whether "bugged" or by design, you're right that S-class upgrades are superior to X-class for the Neutron Cannon. Which is why I asked for corrected stats for the _S_-class upgrades.

**Comment by skyhirider** [comment]
I had a look at the cannon 4 csv and it indeed seems wrong, as there is no way to tell the damage value bonus from the file.

**Comment by cengelha** [comment]
UP_CANN is known to be outdated. The data are currently from 4.13 but UP_CANN was changed in 4.3. I added/will add a new section in the readme about it and close this as there is nothing I can do about until NMS.py can handle newer versions as well.
